export enum ActionTypeEnum {
  USER_CREATE = 'USER.CREATE',
  USER_UPDATE = 'USER.UPDATE',
  USER_DELETE = 'USER.DELETE',
  TODO_CREATE = 'TODO.CREATE',
  TODO_UPDATE = 'TODO.UPDATE',
  TODO_DELETE = 'TODO.DELETE',
  TODO_ASSIGN = 'TODO.ASSIGNED',
  TODO_COMPLETE = 'TODO.COMPLETED',
}
